name: Build for Debian 11 (musl)

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: debian-11  

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar toolchain musl
        run: rustup target add x86_64-unknown-linux-musl

      - name: Instalar dependências
        run: sudo apt-get update && sudo apt-get install -y musl-tools

      - name: Compilar binário estático
        run: cargo build --release --target x86_64-unknown-linux-musl

      - name: Fazer upload do binário
        uses: actions/upload-artifact@v4
        with:
          name: import_wp-debian11-musl
          path: target/x86_64-unknown-linux-musl/release/import_wp

